# Summary of events will trigger workflow
# Pull request when only opened and targetted for the main branch or 'dev-* (dev-any letters)' or
# feat/** 
# manully triggered or push into main or dev-* or feat/** and no change in any file in the
# path .github/workflows/*
name: Events Demo 1
on:
  pull_request:
    types:
      - opened
    branches:
      - master # main branch
      - 'dev-*' # dev-new
      - 'feat/**' # feat/new feat/new/test
  workflow_dispatch:
  push:
    branches:
      - master # main branch
      - 'dev-*' # dev-new
      - 'feat/**' # feat/new feat/new/test
    paths-ignore:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."